package edu.uclm.esi.videochat;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.Before;
import org.hamcrest.core.Is;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By.ByPartialLinkText;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.w3c.dom.html.HTMLElement;

import edu.uclm.esi.videochat.model.User;
import edu.uclm.esi.videochat.springdao.UserRepository;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
public class LoginTest {
  private WebDriver chrome;
  private WebDriver firefox;
  
  @Autowired
  UserRepository userRepo; 
  
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\Antonio Rubio\\Documents\\universidad\\Drivers\\chromedriver.exe");
	System.setProperty("webdriver.gecko.driver", "C:\\Users\\Antonio Rubio\\Documents\\universidad\\Drivers\\geckodriver.exe");
	chrome = new ChromeDriver();
    firefox = new FirefoxDriver();
    js = (JavascriptExecutor) chrome;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    chrome.quit();
    firefox.quit();
  }
  @Test
  public void login() {
    chrome.get("https://localhost:7500/");
    
//    chrome.findElement(By.id("details-button")).click();
//    chrome.findElement(By.id("proceed-link")).click();
    
    
    chrome.manage().window().setSize(new Dimension(1184, 683));
    chrome.findElement(By.cssSelector(".oj-hybrid-padding")).click();
    chrome.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).clear();
    chrome.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).sendKeys("Alejandro");
    chrome.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).clear();
    chrome.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).sendKeys("1234");
    chrome.findElement(By.cssSelector("button")).click();
    
    chrome.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    
    assertThat(chrome.findElement(By.cssSelector(".oj-hybrid-padding > h1")).getText(), is("Zona de conversación"));
  }
  @Test
  public void registro() {
	  Optional<User> lucia = userRepo.findByName("Lucia");
	  if(lucia.isPresent())
		  userRepo.deleteById(lucia.get().getId());
    chrome.get("https://localhost:7500/");
    
    try {
  		Thread.sleep(500);
  	} catch (InterruptedException e) {
  		// TODO Auto-generated catch block
  		e.printStackTrace();
  	}
    
//    chrome.findElement(By.id("details-button")).click();
//    chrome.findElement(By.id("proceed-link")).click();
    WebElement link = chrome.findElement(By.linkText("Crear Cuenta"));
    link.click();
    
    WebElement cajaPwd = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[3]"));
    WebElement cajaPwd2 = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[4]"));
    WebElement cajaEmail = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[2]"));
    WebElement cajaNombre= chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/input[1]"));
    cajaNombre.sendKeys("Lucia");
    cajaEmail.sendKeys("lucia@gmail.com");
    cajaPwd.sendKeys("1234");
    cajaPwd2.sendKeys("1234");
    
    
    
    WebElement boton = chrome.findElement(By.xpath("/html/body/div/oj-module/div[1]/div[2]/div/div/div/button"));
    boton.click();
    
    try {
		Thread.sleep(500);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    assertThat(chrome.switchTo().alert().getText(), is("Registrado correctamente"));
    //assertThat(chrome.findElement(By.cssSelector(".oj-hybrid-padding > h1")).getText(), is("Login"));
  }
  @Test
  public void conversacion() {
	  hacerLogin(chrome, "Alejandro", "1234");
	  hacerLogin(firefox, "poci","1234");
	  
	  try {
			Thread.sleep(500);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	  WebElement poci = chrome.findElement(By.linkText("poci"));
	  poci.click();
	  
	  String mensaje1 = "Hola, poci";
	  WebElement ale = firefox.findElement(By.linkText("Alejandro"));
  }
private void hacerLogin(WebDriver driver, String nombre, String contraseña) {
    driver.get("https://localhost:7500/");
    
//  chrome.findElement(By.id("details-button")).click();
//  chrome.findElement(By.id("proceed-link")).click();
  
  
  driver.manage().window().setSize(new Dimension(1184, 683));
  driver.findElement(By.cssSelector(".oj-hybrid-padding")).click();
  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).clear();
  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(1) > input")).sendKeys(nombre);
  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).clear();
  driver.findElement(By.cssSelector(".oj-sm-12:nth-child(2) > input")).sendKeys(contraseña);
  driver.findElement(By.cssSelector("button")).click();
  
  driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
  
	
}
  
  
  
}
